language: node_js
node_js:
- '0.12'
env:
  global:
    secure: cUekESfFHF7vq8eKOHwAseleH/joUkFs/zN/Rdy6W51c3VEGiPB+fWDFtOzjwv8n5crVtbHKM4YwUSmBHRCrRJf9zs4fV0UjRnLRtrQVf1jOdZlEMolqHp7rj0xvO7kSKDUwRln6L5oB2u2WxGXKd/LCmMEj00WQBLYaHoeXyFnmrHxm1AV73x94fwhksZbAxkEv2HivDvd7MyWZLXuPU33goUtIPV/5COc2NKiB+hAqypVCN2es3GB9STFhTma098qUwKVF8op1SCxOgMbZNoXQZymC8HFYi+lt2ReHJWiNtxwnvBgNShfORTpDgMqJEmNtZASNy2/lsBHNEjQcPBm4XXsoNnIlomeY3J85tlwtSQNsd+FiCFf1HfWRbIhNKBzMf5ah/uR5nzsuyXHyJYwBbqON1phIj1iuPO5XhCsMO8fhGbPEDIwYGRC0+ZL+SkLE7FFY7/v/+rZ8to19CBNId5lrOe3lJOrLzMe265VsVPpEko6C1AXXxGGfDrvCUTgbDyI0FrWxfFi9lkWjyuZG24fAsqEq0ZCrY6NwBG3asj6Q4AF4stqnDS7aodrsp6FQnrUfQhkBNPA5Z3Ae3stGs6mm9MA+Fxlr7lt26ewUNiaki9WUmnAxr0dOJ9rgLmx6BfPlwRZw6sZLF/CtKoAt4pi7cR35dZYL6Q27RVM=
